### ISSUE TITLE
mod request

### ISSUE THREAD

**Issue by rylid-umil** [MaxSMokeSkaarj/SMoA-Modpack#1]
im here to request you to add my mod (new-units) to your mod, and i give you FULL permission to do so. 
since i havent made a factry for them it would be aprreciated if you made a customf actory that creates theese units, or factory that spawns units for free in sandbox mode. thanks in advance! - rylid umil
im requesting this in this way because file uploadig is locked.

**Comment by MaxSMokeSkaarj** [comment]
Rejected. Your mod is under version 135+(V7), you need 105+(V6)
